title: "ETHICAL ARSENAL"
description: "Repository of characteristics for hardware hacking devices, firmwares, and modules."
url: "https://ethical-arsenal.github.io"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
